### ISSUE TITLE
CORS enable at API

### ISSUE THREAD

**Issue by deep-mm** [CSC510-Group-5/URL-Shortner#54]
Currently when calling the API from Angular App, the following error is witnessed:

Access to XMLHttpRequest at 'https://sef22group5.pythonanywhere.com/new/' from origin 'https://deep-mm-csc510-group-5-url-shortner-96rxgpqgprqc7p4g-4200.githubpreview.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
input-long-url.component.ts:60 

My initial understanding is CORS needs to be enabled at API end

**Comment by alunavat** [comment]
They are deployed on different servers right? I think the backend would have to allow our front-end server to connect

**Comment by alunavat** [comment]
There are two options, allow all or allow specific? @akk5597 @rohit97n @psurana-ncsu how do you guys wanna proceed?

**Comment by deep-mm** [comment]
@rohit97n has added CORS at API side to allow front end app to access it.
I have verified it at angular app and it seems to be working

This closing this issue
